---
nifi_version: "2.9.0"
nifi_cluster_node_protocol_port: 8082
nifi_web_http_port: 8080
nifi_web_https_port: 8443
nifi_use_https: false
nifi_zookeeper_connect_string: "{{ groups['zookeeper'] | map('extract', hostvars, 'ansible_host') | map('regex_replace', '^(.*)$', '\\1:2181') | join(',') }}"
# Use SSL port if ZooKeeper SSL is enabled
nifi_zookeeper_connect_string_ssl: "{{ groups['zookeeper'] | map('extract', hostvars, 'ansible_host') | map('regex_replace', '^(.*)$', '\\1:2281') | join(',') }}"
nifi_sensitive_props_key: "nifiproxypass"
nifi_docker_network: "nifi-network"

# Keycloak OIDC Authentication
nifi_use_keycloak: false
keycloak_url: "https://keycloak.example.com"
keycloak_realm: "nifi"
keycloak_client_id: "nifi-client"
keycloak_client_secret: "{{ vault_keycloak_client_secret }}"
nifi_initial_admin: ""  # Keycloak user to set as initial NiFi admin
nifi_sensitive_props_key: "{{ vault_nifi_sensitive_props_key }}"

# Custom SSL Keystore and Truststore (required when nifi_use_keycloak is true)
nifi_ssl_dir: "/opt/nifi/ssl"
nifi_keystore_file: "keystore.jks"
nifi_keystore_path: "{{ nifi_ssl_dir }}/{{ nifi_keystore_file }}"
nifi_keystore_password: "{{ vault_nifi_keystore_password }}"
nifi_keystore_type: "JKS"
nifi_truststore_file: "truststore.jks"
nifi_truststore_path: "{{ nifi_ssl_dir }}/{{ nifi_truststore_file }}"
nifi_truststore_password: "{{ vault_nifi_truststore_password }}"
nifi_truststore_type: "JKS"
