---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: nifi
    image: ubuntu:22.04
    pre_build_image: true
    command: /sbin/init
    args:
      capabilities: SYS_ADMIN
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:rw
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
verifier:
  name: ansible
  playbooks:
    verify: verify.yml
