---
collections:
  - name: community.general
  - name: ansible.posix
  - name: community.podman

roles: {}

# Testing requirements
collections:
  - name: molecule
    version: "5.0"
  - name: molecule-podman
    version: "1.0"
